"""create atletas and centro_treinamento tables

Revision ID: 9e8e3d417dc2
Revises: f265255d83f5
Create Date: 2025-06-09 21:24:41.821870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8e3d417dc2'
down_revision: Union[str, None] = 'f265255d83f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('centro_treinamento_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('atletas_categoria_treinamento_id_fkey'), 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'centros_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.drop_column('atletas', 'categoria_treinamento_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('categoria_treinamento_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key(op.f('atletas_categoria_treinamento_id_fkey'), 'atletas', 'centros_treinamento', ['categoria_treinamento_id'], ['pk_id'])
    op.drop_column('atletas', 'centro_treinamento_id')
    # ### end Alembic commands ###
